[env]
TERM = "xterm-256color"

[terminal]
osc52 = "CopyPaste"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 9

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.75

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" },
  { key = "Return", mods = "Shift", chars = "\u001B\r" },
]

[colors]
[colors.primary]
background = "#121212"
foreground = "#D4D4D4"
dim_foreground = "#8a8a8d"

[colors.cursor]
text = "#121212"
cursor = "#EAEAEA"

[colors.selection]
text = "CellForeground"
background = "#AFAFAF"

[colors.normal]
black = "#333333"
red = "#862020"
green = "#AFAFAF"
yellow = "#EAEAEA"
blue = "#EAEAEA"
magenta = "#932A37"
cyan = "#AFAFAF"
white = "#bebebe"

[colors.bright]
black = "#8a8a8d"
red = "#C73838"
green = "#EAEAEA"
yellow = "#E07924"
blue = "#EFEFEF"
magenta = "#C73838"
cyan = "#EAEAEA"
white = "#eaeaea"
