[env]
TERM = "xterm-256color"

[terminal]
osc52 = "CopyPaste"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 9

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.75

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" },
  { key = "Return", mods = "Shift", chars = "\u001B\r" },
]

[colors]
[colors.primary]
background = "#0e1415"
foreground = "#dee3e5"
dim_foreground = "#bfc8ca"

[colors.cursor]
text = "#0e1415"
cursor = "#82d3e0"

[colors.selection]
text = "CellForeground"
background = "#004f58"

[colors.normal]
black = "#171d1e"
red = "#862020"
green = "#004f58"
yellow = "#82d3e0"
blue = "#82d3e0"
magenta = "#932A37"
cyan = "#004f58"
white = "#dee3e5"

[colors.bright]
black = "#bfc8ca"
red = "#C73838"
green = "#82d3e0"
yellow = "#E07924"
blue = "#82d3e0"
magenta = "#C73838"
cyan = "#82d3e0"
white = "#dee3e5"
