-- Application launchers. Override in bindings.lua if needed.
hl.bind("SUPER + RETURN", hl.dsp.exec_cmd('uwsm-app -- xdg-terminal-exec --dir="$(r2-d2-cmd-terminal-cwd)"'), { description = "Terminal" })
hl.bind("SUPER + B", hl.dsp.exec_cmd("r2-d2-launch-browser"), { description = "Browser" })
hl.bind("SUPER + ALT + B", hl.dsp.exec_cmd("r2-d2-launch-browser --private"), { description = "Browser (private)" })
hl.bind("SUPER + I", hl.dsp.exec_cmd("uwsm-app -- cursor"), { description = "Cursor" })
hl.bind("SUPER + N", hl.dsp.exec_cmd("uwsm-app -- thunar"), { description = "Thunar" })
hl.bind("SUPER + M", hl.dsp.exec_cmd("r2-d2-launch-brook"), { description = "Brook" })
hl.bind("SUPER + CTRL + Y", hl.dsp.exec_cmd("r2-d2-launch-or-focus YouTube uwsm-app -- gtk-launch YouTube"), { description = "YouTube" })
hl.bind("SUPER + CTRL + W", hl.dsp.exec_cmd("r2-d2-launch-or-focus WhatsApp uwsm-app -- gtk-launch WhatsApp"), { description = "WhatsApp" })
hl.bind("SUPER + CTRL + X", hl.dsp.exec_cmd("r2-d2-launch-or-focus X uwsm-app -- gtk-launch X"), { description = "X" })
hl.bind("SUPER + CTRL + T", hl.dsp.exec_cmd("r2-d2-launch-or-focus Telegram uwsm-app -- gtk-launch Telegram"), { description = "Telegram" })
hl.bind("SUPER + CTRL + G", hl.dsp.exec_cmd("r2-d2-launch-or-focus steam uwsm-app -- gtk-launch steam"), { description = "Steam" })
