# Application launchers. Override in bindings.conf if needed.
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(r2-d2-cmd-terminal-cwd)"
bindd = SUPER, B, Browser, exec, r2-d2-launch-browser
bindd = SUPER ALT, B, Browser (private), exec, r2-d2-launch-browser --private
bindd = SUPER, I, Cursor, exec, uwsm-app -- cursor
bindd = SUPER, H, Helium, exec, uwsm-app -- helium-browser
bindd = SUPER, Y, YouTube, exec, r2-d2-launch-or-focus YouTube gtk-launch YouTube
bindd = SUPER CTRL, N, Nautilus, exec, uwsm-app -- nautilus --new-window
bindd = SUPER CTRL, W, WhatsApp, exec, r2-d2-launch-or-focus WhatsApp gtk-launch WhatsApp
bindd = SUPER CTRL, X, X, exec, r2-d2-launch-or-focus X gtk-launch X
bindd = SUPER CTRL, G, Steam, exec, r2-d2-launch-or-focus steam gtk-launch steam
