# Application launchers (Terminal, Browser, File manager, Editor)
# Override in bindings.conf if needed.
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(r2-d2-cmd-terminal-cwd)"
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(r2-d2-cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
bindd = SUPER SHIFT, C, Cursor, exec, uwsm-app -- cursor
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(r2-d2-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, r2-d2-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, r2-d2-launch-browser --private
bindd = SUPER SHIFT, N, Editor, exec, r2-d2-launch-editor
