# Menus
bindd = SUPER, SPACE, Launch apps, exec, r2-d2-launch-walker
bindd = SUPER CTRL, E, Emoji picker, exec, r2-d2-launch-walker -m symbols
bindd = SUPER CTRL, C, Capture menu, exec, r2-d2-menu capture
bindd = SUPER ALT, SPACE, R2-D2 menu, exec, r2-d2-menu
bindd = SUPER, ESCAPE, System menu, exec, r2-d2-menu system
bindld = , XF86PowerOff, Power menu, exec, r2-d2-menu system
bindd = SUPER, K, Show key bindings, exec, r2-d2-menu-keybindings

# Aesthetics
bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, r2-d2-toggle-waybar
bindd = SUPER CTRL, SPACE, Background selector, exec, r2-d2-launch-walker -m menus:r2-d2-background-selector --width 800 --minheight 400
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle
bindd = SUPER SHIFT, BACKSPACE, Toggle workspace gaps, exec, r2-d2-hyprland-workspace-toggle-gaps

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, r2-d2-toggle-notification-silencing
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Toggles
bindd = SUPER CTRL, I, Toggle locking on idle, exec, r2-d2-toggle-idle
bindd = SUPER CTRL, N, Toggle nightlight, exec, r2-d2-toggle-nightlight
bindd = SUPER CTRL, O, Toggle menu, exec, r2-d2-menu toggle
bindd = SUPER CTRL, Backspace, Toggle monitor scaling, exec, r2-d2-hyprland-monitor-scaling-toggle
bindd = SUPER CTRL, M, Apply monitor layout (external left), exec, r2-d2-hyprland-monitor-layout external-left
bindd = SUPER CTRL ALT, Backspace, Toggle single-window square aspect, exec, r2-d2-hyprland-window-single-square-aspect-toggle

# Captures
bindd = , PRINT, Screenshot, exec, r2-d2-cmd-screenshot
bindd = ALT, PRINT, Screenrecording, exec, r2-d2-menu screenrecord
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a

# File sharing
bindd = SUPER CTRL, S, Share, exec, r2-d2-menu share

# Waybar-less information
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send "    $(date +"%A %H:%M  —  %d %B W%V %Y")"
bindd = SUPER CTRL ALT, B, Show battery remaining, exec, notify-send "󰁹    Battery is at $(r2-d2-battery-remaining)%"

# Control panels
bindd = SUPER CTRL, A, Audio controls, exec, r2-d2-launch-audio
bindd = SUPER CTRL, B, Bluetooth controls, exec, r2-d2-launch-bluetooth
bindd = SUPER CTRL, W, Wifi controls, exec, r2-d2-launch-wifi
bindd = SUPER CTRL, T, Activity, exec, r2-d2-launch-tui btop

# Dictation
bindd = SUPER CTRL, X, Toggle dictation, exec, voxtype record toggle

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bindd = SUPER CTRL, L, Lock system, exec, r2-d2-lock-screen
