[tools]
lock_screen = false
screenshot = false
battery_remaining = true
toggle_nightlight = false
toggle_waybar = false
toggle_notification_silencing = false
notification_dismiss = false
theme_set_background = false
desktop_windows = false
system_reboot = true
system_shutdown = true
open_application = false
theme_set_accent = false
volume_set = false
volume_toggle_mute = false
media_play_pause = false
clipboard_set = false