# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# All the default R2-D2 aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.config/bash/rc

# Load SSH keys into agent (keychain)
if command -v keychain &>/dev/null; then
  eval $(keychain --eval --agents ssh id_git_ssh 2>/dev/null)
  eval $(keychain --eval --agents ssh id_rsa_ssh_login 2>/dev/null)
  eval $(keychain --eval --agents ssh id_ssh_login 2>/dev/null)
fi

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'
