#!/bin/bash

run_logged $R2D2_INSTALL/config/config.sh
run_logged $R2D2_INSTALL/config/default-config.sh
run_logged $R2D2_INSTALL/config/theme.sh
run_logged $R2D2_INSTALL/config/branding.sh
run_logged $R2D2_INSTALL/config/git.sh
run_logged $R2D2_INSTALL/config/gpg.sh
run_logged $R2D2_INSTALL/config/timezones.sh
run_logged $R2D2_INSTALL/config/increase-sudo-tries.sh
run_logged $R2D2_INSTALL/config/increase-lockout-limit.sh
run_logged $R2D2_INSTALL/config/ssh-flakiness.sh
run_logged $R2D2_INSTALL/config/increase-file-watchers.sh
run_logged $R2D2_INSTALL/config/detect-keyboard-layout.sh
run_logged $R2D2_INSTALL/config/xcompose.sh
run_logged $R2D2_INSTALL/config/docker.sh
run_logged $R2D2_INSTALL/config/flatpak.sh
run_logged $R2D2_INSTALL/config/mimetypes.sh
run_logged $R2D2_INSTALL/config/terminal-default.sh
run_logged $R2D2_INSTALL/config/walker-elephant.sh
run_logged $R2D2_INSTALL/config/fast-shutdown.sh
run_logged $R2D2_INSTALL/config/input-group.sh
run_logged $R2D2_INSTALL/config/makima.sh
run_logged $R2D2_INSTALL/config/kernel-modules-hook.sh
run_logged $R2D2_INSTALL/config/powerprofilesctl-rules.sh
run_logged $R2D2_INSTALL/config/wifi-powersave-rules.sh
run_logged $R2D2_INSTALL/config/plocate-ac-only.sh
run_logged $R2D2_INSTALL/config/hardware/network.sh
run_logged $R2D2_INSTALL/config/hardware/set-wireless-regdom.sh
run_logged $R2D2_INSTALL/config/hardware/bluetooth.sh
run_logged $R2D2_INSTALL/config/hardware/printer.sh
run_logged $R2D2_INSTALL/config/hardware/usb-autosuspend.sh
run_logged $R2D2_INSTALL/config/hardware/ignore-power-button.sh
run_logged $R2D2_INSTALL/config/hardware/vulkan.sh
run_logged $R2D2_INSTALL/config/hardware/fix-synaptic-touchpad.sh
