import QtQuick 2.0
// AUTO-GENERATED by matugen from sddm-palette.qml — do not edit.
// R2-D2 SDDM theme palette. Deployed to /usr/share/sddm/themes/r2-d2/ by
// r2-d2-refresh-sddm at install/update (system-managed, not on every wallpaper
// change). See docs/VISUAL-CONTRACT.md.
QtObject {
    property color background: "{{colors.background.default.hex}}"
    property color surface: "{{colors.surface_container.default.hex}}"
    property color outline: "{{colors.outline.default.hex}}"
    property color foreground: "{{colors.on_background.default.hex}}"
    property color onSurface: "{{colors.on_surface.default.hex}}"
    property color primary: "{{colors.primary.default.hex}}"
    property color onPrimary: "{{colors.on_primary.default.hex}}"
    property color error: "{{colors.error.default.hex}}"
}
