import QtQuick 2.0
// AUTO-GENERATED by matugen from sddm-palette.qml — do not edit.
// R2-D2 SDDM theme palette. Deployed to /usr/share/sddm/themes/r2-d2/ by
// r2-d2-refresh-sddm at install/update (system-managed, not on every wallpaper
// change). See docs/VISUAL-CONTRACT.md.
QtObject {
    property color background: "#0e1415"
    property color surface: "#1b2122"
    property color outline: "#899294"
    property color foreground: "#dee3e5"
    property color onSurface: "#dee3e5"
    property color primary: "#82d3e0"
    property color onPrimary: "#00363d"
    property color error: "#ffb4ab"
}
